# Numpy
## Ejercicios prácticos

---
### Utiliza Python y Numpy para realizar las siguientes operaciones:
1. Dado el arreglo `a = np.array([1, 2, 3, 4])`, determina si ninguno de los elementos es cero.
2. Dado el arreglo `a = np.array([0, 0, 2, 0])`, determina si contiene algún elemento que no sea cero.
3. Analiza el arreglo `a = np.array([1, 2, np.nan, np.inf])` y determina si contiene valores que sean infinitos o valores no numéricos (NaN).
4. Dado el arreglo `a = np.array([1, 2, np.inf])`, determina si contiene valores infinitos.
5. Dado el arreglo `a = np.array([1, np.nan, 3])`, determina si contiene valores NaN.
6. Dados los arreglos `a = np.array([1, 3, 5])` y `b = np.array([2, 3, 4])`, realiza una comparación elemento a elemento contemplando mayor, mayor o igual, menor y menor o igual.
7. Crea un arreglo que contenga los valores 1, 7, 13 y 105, y determina la cantidad de memoria que ocupa el arreglo.
8. Crea un arreglo de 10 ceros; uno de 10 unos; y uno de 10 cincos.
9. Crea un arreglo que contenga todos los números enteros entre 30 y 70.
10. Crea un arreglo que contenga los números pares entre 30 y 70.
11. Crea una matriz identidad de 3x3.
12. Genera un número aleatorio entre 0 y 1.
13. Crea un arreglo de 15 números aleatorios tomados de una distribución normal estándar.
14. Crea un arreglo con valores entre 15 y 55, e imprime todos los valores excepto el primero y el último.
15. Crea un vector (arreglo) de longitud 10 con valores equitativamente distribuidos entre 5 y 50.
16. Crea un vector con valores de 0 a 20, y cambia el signo de los números de 9 a 15.
17. Convierte el arreglo `a = np.array([1, 2, 3])` a una lista de Python.
18. Convierte la lista `l = [1, 2, 3]` a un arreglo de Numpy.
19. Dada la matriz `m = np.array([[1, 2], [3, 4]])`, verifica qué números son pares y almacena los resultados en otra matriz.
20. Dado el arreglo `m = np.array([[1, 2, 3], [4, 5, 6]])`, encuentra el número de filas y columnas de la matriz.

In [21]:
import numpy as np

In [22]:
# ejercicio 1
a = np.array([1, 2, 3, 4])
np.all(a)

np.True_

In [23]:
# ejercicio 2 
a = np.array([0, 0, 2, 0])
np.any(a)


np.True_

In [24]:
# ejercicio 3
a = np.array([1, 2, np.nan, np.inf])
print("donde hay nans?:", np.isnan(a))
print("donde hay infinitos:", np.isinf(a))

donde hay nans?: [False False  True False]
donde hay infinitos: [False False False  True]


In [25]:
# ejercicio 4
a = np.array([1, 2, np.inf])
infinitos_bool = np.isinf(a)
np.any(infinitos_bool)

np.True_

In [26]:
# ejercicio 5
a = np.array([1, np.nan, 3])
NaN_bool = np.isnan(a)
np.any(NaN_bool)

np.True_

In [27]:
# ejercicio 6
a = np.array([1, 3, 5])
b = np.array([2, 3, 4])

print("a es mayor que b?", a > b)
print("a es mayor o igual que b?", a >= b)
print("a es menor que b?", a < b)
print("a es menor o igual que b?", a <= b)


a es mayor que b? [False False  True]
a es mayor o igual que b? [False  True  True]
a es menor que b? [ True False False]
a es menor o igual que b? [ True  True False]


In [28]:
# ejercicio 7
a = np.array([1, 7, 13, 105])

print("Memoria que ocupa el arreglo en bytes:", a.nbytes)

Memoria que ocupa el arreglo en bytes: 32


In [29]:
# ejercicio 8
arreglo_ceros = np.zeros(10)
arreglo_unos = np.ones(10)
arreglo_cincos = np.full(10, 5) 

print("10 Ceros:", arreglo_ceros)
print("10 Unos:", arreglo_unos)
print("10 Cincos:", arreglo_cincos)

10 Ceros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
10 Unos: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
10 Cincos: [5 5 5 5 5 5 5 5 5 5]


In [30]:
# ejercicio 9
arreglo_rango = np.arange(30, 71)

print(arreglo_rango)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [31]:
# ejercicio 10
arreglo_pares = np.arange(30, 71, 2)

print(arreglo_pares)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [32]:
# ejercicio 11
matriz_identidad = np.eye(3)

print(matriz_identidad)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [33]:
# ejercicio 12
numero_al_azar = np.random.rand()
print(numero_al_azar)

0.911236712037075


In [34]:
# ejercicio 13
arreglo_normal = np.random.randn(15)

print(arreglo_normal)

[ 1.43947691 -0.66728945  0.1343866   0.31376661  0.4646413   0.00649444
  0.05269884 -0.34998348  0.85933853 -0.1338988  -1.49949892  0.32313935
  0.20502417  0.11168308  2.40558907]


In [35]:
# ejercicio 14
arreglo_15_55 = np.arange(15, 56)

print(arreglo_15_55[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [36]:
# ejercicio 15
arreglo_equitativo = np.linspace(5, 50, 10)

print(arreglo_equitativo)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [37]:
# ejercicio 16
arreglo_20 = np.arange(21)
arreglo_20[9:16] *= -1
print(arreglo_20)

[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [38]:
# ejercicio 17
a = np.array([1, 2, 3])
lista_normal = a.tolist()
print("tipo de dato:", type(lista_normal))
print (lista_normal)

tipo de dato: <class 'list'>
[1, 2, 3]


In [39]:
# ejercicio 18
l = [1, 2, 3]
array_l = np.array(l)
type(array_l)
array_l

array([1, 2, 3])

In [40]:
# ejercicio 19
m = np.array([[1, 2],
              [3, 4]])
matriz_resultado = (m % 2 == 0)
matriz_resultado


array([[False,  True],
       [False,  True]])

In [41]:
# ejercicio 20
m = np.array([[1, 2, 3],
              [4, 5, 6]])
dimensiones = m.shape
print("numero de filas y columnas de la matriz", dimensiones)

numero de filas y columnas de la matriz (2, 3)
